# Automatically generated by configure - do not modify
TARGET_TILEGX=y
TARGET_NAME=tilegx
TARGET_BASE_ARCH=tilegx
TARGET_ABI_DIR=tilegx
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-tilegx"
CONFIG_LINUX_USER=y
CONFIG_I386_DIS=y
LDFLAGS+= -Wl,-Ttext-segment=0x60000000
QEMU_CFLAGS+=
