# Automatically generated by configure - do not modify
TARGET_ALPHA=y
TARGET_NAME=alpha
TARGET_BASE_ARCH=alpha
TARGET_ABI_DIR=alpha
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-alpha"
CONFIG_LINUX_USER=y
CONFIG_I386_DIS=y
CONFIG_ALPHA_DIS=y
LDFLAGS+= -Wl,-Ttext-segment=0x60000000
QEMU_CFLAGS+=
