# Automatically generated by configure - do not modify
TARGET_S390X=y
TARGET_NAME=s390x
TARGET_BASE_ARCH=s390x
TARGET_ABI_DIR=s390x
TARGET_WORDS_BIGENDIAN=y
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-s390x"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/yangye/secure-vhost/qemu/gdb-xml/s390x-core64.xml /home/yangye/secure-vhost/qemu/gdb-xml/s390-acr.xml /home/yangye/secure-vhost/qemu/gdb-xml/s390-fpr.xml /home/yangye/secure-vhost/qemu/gdb-xml/s390-vx.xml /home/yangye/secure-vhost/qemu/gdb-xml/s390-cr.xml /home/yangye/secure-vhost/qemu/gdb-xml/s390-virt.xml /home/yangye/secure-vhost/qemu/gdb-xml/s390-gs.xml
CONFIG_I386_DIS=y
CONFIG_S390_DIS=y
LDFLAGS+= -Wl,-Ttext-segment=0x60000000
QEMU_CFLAGS+=
