# Automatically generated by configure - do not modify
TARGET_MICROBLAZE=y
TARGET_NAME=microblazeel
TARGET_BASE_ARCH=microblaze
TARGET_ABI_DIR=microblaze
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-microblazeel"
CONFIG_LINUX_USER=y
TARGET_HAS_BFLT=y
CONFIG_I386_DIS=y
CONFIG_MICROBLAZE_DIS=y
LDFLAGS+= -Wl,-Ttext-segment=0x60000000
QEMU_CFLAGS+=
